from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from enum import Enum

from hyperbot.vacuum.vacuum_state import VacuumCoinState
from hyperbot.vacuum.binance_state import BinanceBookState
# Note: Import VacuumConfig conditionally if needed to avoid circular dep, or pass as Any/Dict

from hyperbot.vacuum.lir_calculator import LIRSignal

@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    side: str          # "buy" or "sell"
    strategy_name: str # e.g. "fade", "break_strat"
    confidence: float  # 0.0 - 1.0
    reason: str        # Description for logs
    metadata: Dict[str, Any] = field(default_factory=dict) # Extra data like wall prices

@dataclass
class StrategyContext:
    """Context passed to strategies for decision making."""
    symbol: str
    hyper_state: VacuumCoinState
    binance_state: Optional[BinanceBookState]
    config: Any        # VacuumConfig object
    now_ms: int
    lir: Optional[LIRSignal] = None
    
    # Common derived metrics helper
    @property
    def has_binance(self) -> bool:
        return self.binance_state is not None and self.binance_state.is_ready()

class BaseStrategy(ABC):
    """Abstract base class for all entry strategies."""
    
    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.enabled = config.get("enabled", False)
        self.name = "base"

    @abstractmethod
    def check(self, ctx: StrategyContext) -> Optional[StrategySignal]:
        """
        Check entry conditions.
        Returns Signal if entry triggers, None otherwise.
        """
        pass
